version: '3'
services:
  nginxreverseproxy:
    image: "nginx:1.15"
    container_name: nginxreverseproxy
    ports:
      - "8000:8000"
    #  - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: always
    networks:
      - backend
    depends_on:
      - mongo
      - elasticsearch
      - muresearch
  muresearchalgo:
    image: "bamboovir/muresearchalgo:latest"
    container_name: muresearchalgo
    ports:
      - "5000:5000"
    #expose: # for deploy
    #  - "5000"
    env_file:
      - .env
    environment:
      - mongo_host=mongo
      - mongo_port=27017
      - mongo_username=${DB_USERNAME}
      - mongo_password=${DB_PASSWORD}
    networks: 
      - backend
  muresearch:
    image: "bamboovir/muresearchboost:latest"
    container_name: muresearch
    ports:
      - "8080:8080"
    #expose: # for deploy
    #  - "8080"
    restart: always
    env_file:
      - .env
    environment:
      - mongo_address=mongo
      - elastic_address=elasticsearch
      - spring_data_mongodb_host=mongo
      - spring_data_elasticsearch_cluster-nodes=elasticsearch:9300
      - spring_data_mongodb_username=${DB_USERNAME}
      - spring_data_mongodb_password=${DB_PASSWORD}
    networks:
      - backend
    depends_on:
      - mongo
      - elasticsearch
  mongo:
    image: "mongo:3.4"
    container_name: mongodb
    ports:
      - "27017:27017"
    #expose: # for deploy
    #  - "27017"
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - '/var/mongo_data:/data/db'
      - '/var/mongo_backup:/backup'
    networks:
      - backend
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.0"
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    #expose: # for deploy
    #  - "9200"
    #  - "9300"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/backup
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - '/var/elasticsearch_data:/usr/share/elasticsearch/data'
      - '/var/elasticsearch_backup:/backup'

    networks:
      - backend

networks:
  backend:
    driver: "bridge"